
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Запускать на пуш в ветку main
  pull_request:
    branches:
      - main  # Запускать на pull request в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Set up Python
        uses: actions/setup-python@v4  # Настройка Python
        with:
          python-version: '3.x'  # Указываем версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Обновляем pip
          pip install -r requirements.txt  # Устанавливаем зависимости из requirements.txt

      - name: Run tests
        run: |
          # Запускаем все тесты в папке tests для всех файлов с тестами
          python -m unittest discover -s tests -p "*.py"  # Указываем шаблон для всех файлов с тестами

      - name: Upload test results
        if: failure()  # Если тесты не прошли, загружаем результаты
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./test-results.xml  # Укажите путь к файлу с результатами, если нужно

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Этот job запускается только после успешного завершения build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          # Пример команды деплоя (замените на свои)
          echo "Deploying to production server..."
